export const FACTS = [
  // ─── Space & Astronomy ──────────────────────────────────────────────────────
  { text: "A day on Venus is longer than a year on Venus — it takes 243 Earth days to rotate once but only 225 Earth days to orbit the Sun.", category: "Space" },
  { text: "There are more stars in the observable universe than grains of sand on all of Earth's beaches — roughly 10²⁴ stars.", category: "Space" },
  { text: "Neutron stars are so dense that a teaspoon of their material would weigh about 10 million tons.", category: "Space" },
  { text: "The footprints left by Apollo astronauts on the Moon will last at least 100 million years — no wind or water to erode them.", category: "Space" },
  { text: "If you removed all the empty space from every atom in every human, the entire human race would fit inside a sugar cube.", category: "Space" },
  { text: "The Sun makes up 99.86% of the total mass of the entire solar system.", category: "Space" },
  { text: "Light from the Sun takes 8 minutes 20 seconds to reach Earth, but 4.3 years to reach the nearest other star.", category: "Space" },
  { text: "Saturn's rings are only about 20 metres thick on average, yet span up to 282,000 km across.", category: "Space" },
  { text: "A year on Mercury lasts 88 Earth days, but a single Mercurian day (sunrise to sunrise) lasts 176 Earth days.", category: "Space" },
  { text: "Olympus Mons on Mars is about three times the height of Everest — the tallest known volcano in the solar system.", category: "Space" },
  { text: "The Milky Way galaxy is about 13.6 billion years old — nearly as old as the universe itself.", category: "Space" },
  { text: "If the Sun were the size of a door, Earth would be about the size of a coin.", category: "Space" },
  { text: "There is a giant cloud of alcohol in space — the Sagittarius B2 cloud contains 10 billion billion billion litres of vinyl alcohol.", category: "Space" },
  { text: "The universe is expanding — distant galaxies appear to recede faster than light because space itself stretches.", category: "Space" },
  { text: "It would take about 100,000 years to travel across the Milky Way at the speed of light.", category: "Space" },
  { text: "The event horizon of a black hole is the point of no return — not even light can escape once it crosses that boundary.", category: "Space" },
  { text: "Pluto is smaller than the United States — its diameter is about 2,377 km, while the US is about 4,500 km wide.", category: "Space" },
  { text: "Jupiter's Great Red Spot is a storm wider than Earth that has been raging for at least 350 years.", category: "Space" },
  { text: "The coldest known place in the universe is the Boomerang Nebula at just 1 kelvin (−272 °C).", category: "Space" },
  { text: "A pulsar spins so fast and precisely that it is more accurate than an atomic clock.", category: "Space" },
  // ─── Human Body ─────────────────────────────────────────────────────────────
  { text: "Your body produces about 25 million new cells every second — more than the entire population of Canada, per second.", category: "Human Body" },
  { text: "The human brain has about 86 billion neurons and can generate up to 23 watts of electrical power while awake.", category: "Human Body" },
  { text: "Bones are about 5 times stronger than steel of the same density — pound for pound, bone outperforms concrete.", category: "Human Body" },
  { text: "The human eye can distinguish approximately 10 million different colours.", category: "Human Body" },
  { text: "Your heart beats around 100,000 times per day, pumping ~7,500 litres of blood through 96,000 km of blood vessels.", category: "Human Body" },
  { text: "Stomach acid is strong enough to dissolve a razor blade — the stomach lining renews itself every 4 days to prevent self-digestion.", category: "Human Body" },
  { text: "Humans share about 60% of their DNA with bananas.", category: "Human Body" },
  { text: "The human nose can detect over 1 trillion different smells.", category: "Human Body" },
  { text: "Fingernails grow about 3.5 mm per month — roughly 4 times faster than toenails.", category: "Human Body" },
  { text: "The average person walks about 100,000 miles in a lifetime — enough to circle the Earth four times.", category: "Human Body" },
  { text: "Babies are born with around 270 bones; adults have only 206 because many fuse during childhood.", category: "Human Body" },
  { text: "The human skeleton is completely replaced via bone remodelling roughly every 10 years.", category: "Human Body" },
  { text: "A sneeze travels at about 160 km/h and can contain up to 100,000 germs.", category: "Human Body" },
  { text: "The liver performs over 500 distinct functions, including filtering about 1.4 litres of blood per minute.", category: "Human Body" },
  { text: "Your ears never stop working — even during sleep, your brain filters sound rather than your ears switching off.", category: "Human Body" },
  { text: "The small intestine is about 6–7 metres long, yet coils tightly to fit inside the abdomen.", category: "Human Body" },
  { text: "Humans are the only animals known to blush.", category: "Human Body" },
  { text: "The cornea is the only tissue in the human body with no blood supply — it gets oxygen directly from the air.", category: "Human Body" },
  { text: "Your brain is about 73% water; being just 2% dehydrated is enough to impair attention and memory.", category: "Human Body" },
  { text: "The total surface area of your two lungs is roughly equal to the size of a tennis court.", category: "Human Body" },
  { text: "The human body contains enough carbon to make about 9,000 pencils.", category: "Human Body" },
  { text: "Your body has more bacterial cells than human cells — roughly 1.3 bacteria for every 1 human cell.", category: "Human Body" },
  // ─── Animals ────────────────────────────────────────────────────────────────
  { text: "Octopuses have three hearts, blue blood, and nine brains — one central brain plus one in each arm.", category: "Animals" },
  { text: "A group of flamingos is called a flamboyance.", category: "Animals" },
  { text: "Elephants are the only non-human animals known to perform death rituals — they grieve and revisit the bones of their deceased.", category: "Animals" },
  { text: "A sloth moves so slowly that algae grows on its fur, providing natural camouflage.", category: "Animals" },
  { text: "Crows can recognise human faces and hold grudges against people who have wronged them.", category: "Animals" },
  { text: "Mantis shrimp can punch at 80 km/h with the force of a bullet — strong enough to shatter aquarium glass.", category: "Animals" },
  { text: "Cows have best friends and become significantly stressed when separated from them.", category: "Animals" },
  { text: "Tardigrades (water bears) can survive outer space, near absolute zero, boiling water, and lethal radiation.", category: "Animals" },
  { text: "The blue whale's heart is so large that a human could crawl through its main arteries.", category: "Animals" },
  { text: "Dogs can smell about 100,000 times better than humans — they have up to 300 million olfactory receptors.", category: "Animals" },
  { text: "Butterflies taste with their feet — taste sensors on their tarsi identify plants for feeding and egg-laying.", category: "Animals" },
  { text: "A shrimp's heart is located in its head.", category: "Animals" },
  { text: "Sharks are older than trees — sharks have existed for ~450 million years; trees for only ~350 million.", category: "Animals" },
  { text: "Sea otters hold hands while sleeping to prevent drifting apart from one another.", category: "Animals" },
  { text: "Bees can recognise human faces using similar neural processes to humans.", category: "Animals" },
  { text: "Dolphins use unique whistles as names to individually identify each other.", category: "Animals" },
  { text: "The pistol shrimp snaps its claw so fast it creates a cavitation bubble briefly hotter than the surface of the Sun.", category: "Animals" },
  { text: "Snails can sleep for up to 3 years during drought periods.", category: "Animals" },
  { text: "A group of owls is called a parliament.", category: "Animals" },
  { text: "Axolotls can regrow not just limbs but also parts of their heart and brain.", category: "Animals" },
  { text: "The immortal jellyfish (Turritopsis dohrnii) can reverse its life cycle and potentially live indefinitely.", category: "Animals" },
  { text: "A group of pugs is called a grumble.", category: "Animals" },
  { text: "Wombats produce cube-shaped droppings — the only animal on Earth known to do so.", category: "Animals" },
  // ─── History ────────────────────────────────────────────────────────────────
  { text: "Oxford University is older than the Aztec Empire — teaching began at Oxford around 1096; the Aztec Empire started around 1428.", category: "History" },
  { text: "Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid of Giza.", category: "History" },
  { text: "The Great Wall of China is not visible from space with the naked eye — this is a widespread myth.", category: "History" },
  { text: "Vikings did not wear horned helmets — that image was invented by a 19th-century costume designer.", category: "History" },
  { text: "Napoleon was actually average height for his time — about 5 ft 7 in (170 cm). The short Napoleon myth was partly British propaganda.", category: "History" },
  { text: "The shortest war in history was the Anglo-Zanzibar War of 1896, lasting between 38 and 45 minutes.", category: "History" },
  { text: "The world's oldest known recipe is for beer — a 4,000-year-old Sumerian tablet includes brewing instructions.", category: "History" },
  { text: "The Eiffel Tower can be 15 cm taller in summer because heat makes the iron expand.", category: "History" },
  { text: "The first computer bug was a literal bug — in 1947, Grace Hopper's team found a moth trapped inside Harvard's Mark II computer.", category: "History" },
  { text: "Woolly mammoths were still alive when the Great Pyramid of Giza was being built.", category: "History" },
  { text: "Nintendo was founded in 1889 — originally as a playing card company in Kyoto, Japan.", category: "History" },
  { text: "Ancient Romans used crushed mouse brains as toothpaste.", category: "History" },
  { text: "Forks were once considered blasphemous in medieval Europe — seen as artificial hands usurping God's design.", category: "History" },
  { text: "A jockey named Frank Hayes won a race at Belmont Park in 1923 despite having died of a heart attack mid-race.", category: "History" },
  { text: "The Great Fire of London in 1666 destroyed 13,200 houses and 87 churches but officially killed fewer than 10 people.", category: "History" },
  { text: "Coca-Cola was originally green.", category: "History" },
  { text: "The practice of shaking hands originated to show you were not carrying a weapon.", category: "History" },
  { text: "The first alarm clock could only ring at 4 AM — invented by Levi Hutchins in 1787 solely to wake himself up.", category: "History" },
  { text: "Ancient Greeks believed the brain was a radiator for cooling the blood; Aristotle thought the heart was the seat of intelligence.", category: "History" },
  { text: "Sunglasses were invented in ancient China and Rome — early versions used smoky quartz to cut glare.", category: "History" },
  // ─── Science & Physics ──────────────────────────────────────────────────────
  { text: "A jiffy is an actual unit of time — 1/100th of a second in computing, or the time for light to travel one femtometre in physics.", category: "Science" },
  { text: "Hot water can freeze faster than cold water in certain conditions — this is called the Mpemba effect.", category: "Science" },
  { text: "There are more atoms in a single grain of sand than there are stars in the Milky Way.", category: "Science" },
  { text: "Quantum entanglement allows two particles to instantaneously influence each other regardless of the distance between them.", category: "Science" },
  { text: "From a photon's own frame of reference, it travels from source to destination in zero time.", category: "Science" },
  { text: "Hydrogen makes up about 75% of all normal (baryonic) matter in the universe.", category: "Science" },
  { text: "Theoretically, 1 gram of DNA can store about 215 petabytes — 215 million gigabytes — of data.", category: "Science" },
  { text: "At absolute zero (−273.15 °C), atoms nearly stop moving — but quantum mechanics prevents a complete halt.", category: "Science" },
  { text: "Graphene is a sheet of carbon just one atom thick and about 200 times stronger than steel.", category: "Science" },
  { text: "The placebo effect is so strong that even when patients know a pill is fake it can still provide measurable relief.", category: "Science" },
  { text: "Helium was discovered in space (via solar spectral lines) before it was found on Earth.", category: "Science" },
  { text: "We have mapped less than 20% of Earth's ocean floor — we have better maps of Mars and the Moon.", category: "Science" },
  { text: "Space is completely silent — sound requires molecules to vibrate, and there are none in a vacuum.", category: "Science" },
  { text: "Lightning strikes Earth about 100 times every second — roughly 8 million bolts per day.", category: "Science" },
  { text: "If the history of Earth were compressed into 24 hours, humans would appear at 11:58:43 PM.", category: "Science" },
  { text: "Earth's magnetic poles have reversed hundreds of times in geological history — and are currently shifting.", category: "Science" },
  { text: "Water is the only common substance that naturally exists as solid, liquid, and gas at normal Earth temperatures.", category: "Science" },
  { text: "Oxygen was independently discovered by two scientists (Scheele and Priestley) in 1774 without either knowing about the other.", category: "Science" },
  { text: "The speed of light is exactly 299,792,458 metres per second — a fixed constant that defines the metre itself.", category: "Science" },
  { text: "Dark matter makes up about 27% of the universe, yet has never been directly observed — it is inferred from gravitational effects.", category: "Science" },
  // ─── Geography & Earth ──────────────────────────────────────────────────────
  { text: "Australia is wider than the Moon — Australia spans about 4,000 km; the Moon's diameter is 3,474 km.", category: "Geography" },
  { text: "Canada has more lakes than the rest of the world combined — about 60% of all Earth's lakes are in Canada.", category: "Geography" },
  { text: "Russia spans 11 time zones and covers 17.1 million km² — the largest country on Earth.", category: "Geography" },
  { text: "Vatican City covers just 0.44 km² — smaller than most city parks — yet it is a sovereign nation.", category: "Geography" },
  { text: "Mount Chimborazo in Ecuador is technically the closest point to outer space, not Everest — Earth bulges at the equator.", category: "Geography" },
  { text: "The Sahara Desert is roughly the same size as the contiguous United States.", category: "Geography" },
  { text: "New Zealand was the last large landmass settled by humans — Maori arrived around 1250–1300 AD.", category: "Geography" },
  { text: "The Amazon River discharges more water into the ocean than the next seven largest rivers combined.", category: "Geography" },
  { text: "Antarctica is the world's largest desert — deserts are defined by annual precipitation, not temperature.", category: "Geography" },
  { text: "The Dead Sea is about 34% salt; you float effortlessly and almost nothing can survive in it.", category: "Geography" },
  { text: "There are more public libraries than McDonald's in the United States.", category: "Geography" },
  { text: "If you dug straight through Earth from Spain, you would emerge in the Pacific Ocean, not China.", category: "Geography" },
  { text: "The Hawaiian Islands move toward Japan at about 10 cm per year due to tectonic plate movement.", category: "Geography" },
  { text: "The Pacific Ocean is large enough to fit all of Earth's continents inside it with room to spare.", category: "Geography" },
  { text: "Monaco is smaller than Central Park in New York City, yet is a fully sovereign nation.", category: "Geography" },
  // ─── Mathematics ────────────────────────────────────────────────────────────
  { text: "If you properly shuffle a deck of 52 cards, the resulting order has almost certainly never existed before in history.", category: "Mathematics" },
  { text: "Pi has been calculated to over 100 trillion decimal places and never repeats.", category: "Mathematics" },
  { text: "In a room of just 23 people, there is a 50% chance two people share the same birthday — the Birthday Problem.", category: "Mathematics" },
  { text: "Zero cannot be represented in Roman numerals.", category: "Mathematics" },
  { text: "A googol (10¹⁰⁰) is larger than the estimated number of atoms in the observable universe.", category: "Mathematics" },
  { text: "The number 1 is not prime — primes must have exactly two distinct divisors, and 1 has only one.", category: "Mathematics" },
  { text: "Benford's Law: in many natural datasets, about 30% of numbers start with the digit 1 — far more than the expected 11%.", category: "Mathematics" },
  { text: "The Fibonacci sequence appears in sunflower seeds, pine cones, hurricanes, and spiral galaxies.", category: "Mathematics" },
  { text: "If you folded a piece of paper in half 42 times, the stack would be thick enough to reach the Moon.", category: "Mathematics" },
  { text: "There are more possible chess games than atoms in the observable universe.", category: "Mathematics" },
  { text: "Euler's identity (eⁱᵖ + 1 = 0) links five of the most fundamental constants in mathematics in one equation.", category: "Mathematics" },
  { text: "Cantor proved there are different sizes of infinity — the real numbers are a larger infinity than the integers.", category: "Mathematics" },
  // ─── Language & Linguistics ─────────────────────────────────────────────────
  { text: "Japanese has a word — tsundoku — meaning buying books and letting them pile up unread.", category: "Language" },
  { text: "About 7,000 languages exist today, but roughly half are endangered and could disappear this century.", category: "Language" },
  { text: "The word nice originally meant foolish or silly in Middle English.", category: "Language" },
  { text: "Dreamt is the only common English word ending in the letters mt.", category: "Language" },
  { text: "Hawaiian has only 13 letters — 5 vowels and 8 consonants.", category: "Language" },
  { text: "The word quarantine comes from Italian quarantina — the 40-day isolation Venice required of ships during plague outbreaks.", category: "Language" },
  { text: "More English words begin with S than any other letter.", category: "Language" },
  { text: "The German word Verschlimmbessern means to make something worse while attempting to improve it.", category: "Language" },
  { text: "Finnish has no articles (the / a) and no future tense — context determines both.", category: "Language" },
  { text: "American Sign Language and British Sign Language are mutually unintelligible — sign languages are not universal.", category: "Language" },
  { text: "The longest common English word without a vowel is rhythms.", category: "Language" },
  { text: "The word salary comes from Latin salarium — Roman soldiers were sometimes paid in salt.", category: "Language" },
  { text: "Portuguese saudade describes deep emotional longing for something loved and lost — widely considered untranslatable.", category: "Language" },
  { text: "A pangram uses every letter of the alphabet at least once — The quick brown fox jumps over the lazy dog is the classic English example.", category: "Language" },
  // ─── Food & Nutrition ───────────────────────────────────────────────────────
  { text: "Honey never spoils — archaeologists have found 3,000-year-old honey in Egyptian tombs that is still edible.", category: "Food" },
  { text: "Strawberries are not botanically berries, but bananas, avocados, and watermelons are.", category: "Food" },
  { text: "Almonds are not nuts — they are seeds of a peach-family fruit.", category: "Food" },
  { text: "The Aztecs used cacao beans as currency — chocolate was literally money.", category: "Food" },
  { text: "Ketchup was sold as medicine in the 1830s for diarrhoea, indigestion, and liver problems.", category: "Food" },
  { text: "Carrots were originally purple — orange carrots were selectively bred by Dutch farmers in the 17th century.", category: "Food" },
  { text: "Coffee is the second most traded commodity in the world after crude oil.", category: "Food" },
  { text: "Apples float because they are about 25% air.", category: "Food" },
  { text: "Cucumbers are 96% water — the most water-dense common vegetable.", category: "Food" },
  { text: "Milk protein (casein) is far more effective than water at neutralising capsaicin — the burning compound in chilli peppers.", category: "Food" },
  { text: "The peanut is not a nut but a legume, related to lentils and chickpeas.", category: "Food" },
  { text: "Saffron is the world's most expensive spice — about 70,000 crocus flowers are needed to produce just one pound.", category: "Food" },
  { text: "A lemon contains more sugar than a strawberry by weight — the sourness comes from citric acid, not lack of sugar.", category: "Food" },
  { text: "A cashew nut is actually a seed that hangs below the cashew apple fruit.", category: "Food" },
  { text: "There are over 10,000 known varieties of tomatoes worldwide.", category: "Food" },
  // ─── Technology & Computing ──────────────────────────────────────────────────
  { text: "The first computer mouse was made of wood — Douglas Engelbart's 1964 prototype had a wooden shell with two metal wheels.", category: "Technology" },
  { text: "More data has been created in the last two years than in all previous human history combined.", category: "Technology" },
  { text: "The Apollo 11 guidance computer had less processing power than a modern pocket calculator.", category: "Technology" },
  { text: "Email predates the World Wide Web — the first email was sent in 1971; the Web launched in 1991.", category: "Technology" },
  { text: "Google processes about 8.5 billion searches per day — roughly 99,000 every second.", category: "Technology" },
  { text: "YouTube users upload over 500 hours of video every single minute.", category: "Technology" },
  { text: "The first text message, sent December 3 1992, read Merry Christmas.", category: "Technology" },
  { text: "Wi-Fi technically stands for nothing — it was a marketing brand name, never formally expanded.", category: "Technology" },
  { text: "QWERTY was partly designed to slow typists and prevent mechanical typewriter keys from jamming.", category: "Technology" },
  { text: "The Linux kernel — which powers Android, most web servers, and the ISS — began as a Finnish student's hobby project in 1991.", category: "Technology" },
  { text: "A modern smartphone has more computing power than NASA had when it first landed humans on the Moon.", category: "Technology" },
  { text: "The @ symbol was nearly extinct before email revived it in 1971.", category: "Technology" },
  { text: "The first ever registered domain name was Symbolics.com, on March 15 1985.", category: "Technology" },
  { text: "Bitcoin creator Satoshi Nakamoto has never been identified, and their billions in BTC have never been moved.", category: "Technology" },
  // ─── Psychology & Mind ──────────────────────────────────────────────────────
  { text: "The Dunning-Kruger effect: people with limited knowledge overestimate their ability, while genuine experts underestimate theirs.", category: "Psychology" },
  { text: "The brain is the only organ capable of studying and naming itself.", category: "Psychology" },
  { text: "The human brain is more active during sleep than while watching television.", category: "Psychology" },
  { text: "It takes about 66 days on average to form a new habit — not the popular myth of 21 days.", category: "Psychology" },
  { text: "People are often more creative when slightly tired, because inhibitory mental processes relax.", category: "Psychology" },
  { text: "The peak-end rule: we judge an experience almost entirely by its peak intensity and final moments, not by the average.", category: "Psychology" },
  { text: "Studies consistently show that spending on experiences produces longer-lasting happiness than spending on things.", category: "Psychology" },
  { text: "Decision fatigue is real — decision quality deteriorates steadily throughout the day.", category: "Psychology" },
  { text: "Regular fiction readers score significantly higher on empathy tests.", category: "Psychology" },
  { text: "Blue is the most universally preferred colour across diverse cultures worldwide.", category: "Psychology" },
  { text: "Multitasking is largely a myth — the brain rapidly context-switches rather than truly doing two things simultaneously.", category: "Psychology" },
  { text: "Yawning is contagious between species — dogs yawn in response to human yawns as a form of empathy.", category: "Psychology" },
  { text: "Human memory is reconstructive, not replay — each time we recall a memory, we subtly alter it.", category: "Psychology" },
  { text: "The mere exposure effect: people develop a preference for things simply because they are familiar with them.", category: "Psychology" },
  // ─── Nature & Plants ────────────────────────────────────────────────────────
  { text: "Trees share nutrients and warning signals through underground fungal networks — sometimes called the Wood Wide Web.", category: "Nature" },
  { text: "Pando in Utah — a grove of quaking aspens with a single shared root system — is estimated at 80,000 years old, one of Earth's oldest organisms.", category: "Nature" },
  { text: "Bamboo is the fastest-growing plant on Earth — some species grow up to 91 cm in a single day.", category: "Nature" },
  { text: "The smell of rain — petrichor — comes from a compound called geosmin released by soil bacteria.", category: "Nature" },
  { text: "Venus flytraps can count — they snap shut only after two trigger hairs are touched within 20 seconds, avoiding false alarms from raindrops.", category: "Nature" },
  { text: "The Amazon rainforest produces about 20% of Earth's oxygen and harbours roughly 10% of all species.", category: "Nature" },
  { text: "A single large tree can absorb up to 48 pounds of CO2 per year and live for centuries.", category: "Nature" },
  { text: "Lichens are not one organism — they are a symbiosis of fungus and algae or cyanobacteria.", category: "Nature" },
  { text: "A single oak tree can produce up to 70,000 acorns per year and live for 1,000 years.", category: "Nature" },
  { text: "Grasses evolved long before flowers — grasses appeared about 66–100 million years ago.", category: "Nature" },
  { text: "One acre of trees can produce enough oxygen for 18 people to breathe for an entire year.", category: "Nature" },
  // ─── Art & Music ────────────────────────────────────────────────────────────
  { text: "Beethoven was almost completely deaf when he composed his Ninth Symphony.", category: "Art & Music" },
  { text: "The Mona Lisa has no visible eyebrows — shaving them was fashionable in Renaissance Florence and they may have faded over time.", category: "Art & Music" },
  { text: "Van Gogh sold only one painting in his lifetime — The Red Vineyard in 1890 for 400 francs.", category: "Art & Music" },
  { text: "Salvator Mundi, attributed to Leonardo da Vinci, sold for $450.3 million in 2017 — the most expensive painting ever auctioned.", category: "Art & Music" },
  { text: "Mozart wrote his first symphony at age 8 and his first opera at age 12.", category: "Art & Music" },
  { text: "Michelangelo painted the Sistine Chapel ceiling standing on scaffolding, not lying on his back — a popular misconception.", category: "Art & Music" },
  { text: "Happy Birthday to You was composed in 1893 and was not fully in the public domain until 2015.", category: "Art & Music" },
  { text: "The world's largest musical instrument is the Great Stalacpipe Organ in Luray Caverns, Virginia — its keys strike real stalactites.", category: "Art & Music" },
  { text: "Pablo Picasso's mother said his first word was piz, short for lapiz (pencil in Spanish).", category: "Art & Music" },
  { text: "The Louvre is the world's most visited museum, receiving about 7–9 million visitors each year.", category: "Art & Music" },
  // ─── Sports & Records ─────────────────────────────────────────────────────
  { text: "Golf is one of only two sports played on the Moon — Alan Shepard hit two golf shots on the lunar surface in 1971.", category: "Sports" },
  { text: "The first modern Olympics in Athens (1896) had 14 nations; today over 200 compete.", category: "Sports" },
  { text: "Usain Bolt reached 44.72 km/h during his 100m world record run of 9.58 seconds.", category: "Sports" },
  { text: "Table tennis was originally played with books as bats, champagne corks as balls, and a row of books as the net.", category: "Sports" },
  { text: "The Tour de France covers roughly 3,500 km and burns about 8,000 calories per stage for the cyclists.", category: "Sports" },
  // ─── Inventions & Firsts ────────────────────────────────────────────────────
  { text: "The microwave oven was invented after a researcher noticed radar waves melted a chocolate bar in his pocket.", category: "Inventions" },
  { text: "Post-it notes were invented by accident — a weak adhesive with no obvious use sat in a lab for six years before someone used it to bookmark hymn books.", category: "Inventions" },
  { text: "Velcro was inspired by burdock burrs that stuck to an engineer's dog after a 1941 hike.", category: "Inventions" },
  { text: "The first webcam (1991, Cambridge) was created purely to monitor whether a coffee pot was empty before making the walk to check.", category: "Inventions" },
  { text: "WD-40 stands for Water Displacement, 40th formula — it took 40 attempts to perfect it.", category: "Inventions" },
  { text: "Bubble wrap was originally invented as a textured wallpaper in 1957 — the packaging use came later.", category: "Inventions" },
  { text: "Play-Doh started life as a wallpaper cleaner in the 1950s.", category: "Inventions" },
  { text: "The World Wide Web was invented so physicists at CERN could share research more easily.", category: "Inventions" },
  { text: "The first product commercially scanned with a barcode was a pack of Wrigley's gum in an Ohio supermarket in 1974.", category: "Inventions" },
  { text: "Superglue was discovered accidentally in 1942 while trying to make clear plastic gun sights.", category: "Inventions" },
  // ─── Society & Economics ────────────────────────────────────────────────────
  { text: "More people have mobile phones than toilets — ~6 billion people have phones but only ~4.5 billion have access to safe sanitation.", category: "Society" },
  { text: "About 40% of all food produced globally is wasted — more than enough to feed every hungry person on Earth twice over.", category: "Society" },
  { text: "The wealthiest 1% of humans own more than the bottom 50% combined.", category: "Society" },
  { text: "IKEA's catalogue was once the most-printed document in the world, surpassing the Bible in annual print runs.", category: "Society" },
  { text: "In 2024, the global video games industry generated more revenue than movies and music combined.", category: "Society" },
  { text: "About 8 million tonnes of plastic enter the world's oceans every year.", category: "Society" },
  { text: "There are more vacant homes in the United States than there are homeless people.", category: "Society" },
  // ─── Quirky & Surprising ────────────────────────────────────────────────────
  { text: "It is impossible to hum while holding your nose closed — try it.", category: "Quirky" },
  { text: "A day on Earth was once only 18 hours long — the Moon's pull has been gradually slowing Earth's rotation.", category: "Quirky" },
  { text: "The total weight of all ants on Earth is estimated to rival or exceed the total weight of all humans.", category: "Quirky" },
  { text: "A bolt of lightning is about 5 times hotter than the surface of the Sun — reaching ~30,000 K.", category: "Quirky" },
  { text: "The fax machine was invented in 1843 — 33 years before Alexander Graham Bell invented the telephone.", category: "Quirky" },
  { text: "Scotland's national animal is the unicorn.", category: "Quirky" },
  { text: "The average cloud weighs about 500,000 kg — roughly the same as 80 adult elephants.", category: "Quirky" },
  { text: "Competitive art used to be an Olympic event — medals were awarded for architecture, literature, music, painting, and sculpture from 1912 to 1948.", category: "Quirky" },
  { text: "A single cloud droplet is so tiny that roughly one million of them are needed to form a single raindrop.", category: "Quirky" },
  { text: "The inventor of the Frisbee requested that his ashes be made into Frisbees after his death — and they were.", category: "Quirky" },
  { text: "Humans are the only animals that cook their food — cooking is believed to have driven the rapid expansion of the human brain.", category: "Quirky" },
  { text: "Glass is technically an amorphous solid, not a liquid. Old windows look thicker at the bottom because of how they were made, not because glass flows.", category: "Quirky" },
  // ─── Space & Astronomy (continued) ──────────────────────────────────────────
  { text: "The International Space Station travels at about 28,000 km/h and orbits Earth roughly 16 times every 24 hours.", category: "Space" },
  { text: "Astronauts on the ISS witness about 16 sunrises and 16 sunsets every single day.", category: "Space" },
  { text: "Venus spins in the opposite direction to most planets — on Venus the Sun rises in the west and sets in the east.", category: "Space" },
  { text: "Uranus rotates on its side with an axial tilt of 98°, meaning one of its poles faces the Sun for half of the planet's year.", category: "Space" },
  { text: "The largest known star, UY Scuti, is so large that if it replaced our Sun, it would swallow Jupiter's entire orbit.", category: "Space" },
  { text: "There are more possible star configurations in the Milky Way than there have been seconds since the Big Bang.", category: "Space" },
  { text: "Space is not totally empty — the average region of outer space contains about 5 hydrogen atoms per cubic metre.", category: "Space" },
  { text: "Mars has the longest valley system in the solar system — Valles Marineris stretches 4,000 km, the width of the United States.", category: "Space" },
  { text: "Neptune was the first planet predicted mathematically before it was observed — astronomers noted Uranus wobbling and calculated where something must be pulling it.", category: "Space" },
  { text: "Saturn is the only planet in our solar system less dense than water — it would float if you had a bathtub big enough.", category: "Space" },
  // ─── Human Body (continued) ─────────────────────────────────────────────────
  { text: "The human body has about 37 trillion cells — if you counted one per second it would take over a million years.", category: "Human Body" },
  { text: "Your eyes are the only part of your brain that you can actually see — the retina is an outgrowth of brain tissue.", category: "Human Body" },
  { text: "The human tongue has about 10,000 taste buds, each replaced roughly every two weeks.", category: "Human Body" },
  { text: "Goosebumps are a vestigial reflex from our hairier ancestors — the raised hairs made them look larger to predators.", category: "Human Body" },
  { text: "The average human produces about 1 to 1.5 litres of saliva per day — enough to fill two soup mugs.", category: "Human Body" },
  { text: "Bone marrow produces about 2 million red blood cells every second to replace those that die.", category: "Human Body" },
  { text: "Teeth are not bones — they are made of dentin and enamel and cannot repair themselves the way bones do.", category: "Human Body" },
  { text: "Humans are the only primates with a chin — no other ape or ancient hominin had one; its purpose is still debated.", category: "Human Body" },
  { text: "The average adult has about 2 square metres of skin — roughly the area of a single bed sheet.", category: "Human Body" },
  { text: "Your kidneys filter about 200 litres of blood every single day — about 50 times the body's total blood volume.", category: "Human Body" },
  // ─── Animals (continued) ────────────────────────────────────────────────────
  { text: "Elephants are the only mammals that cannot jump — their bones simply aren't built for it.", category: "Animals" },
  { text: "A group of cats is called a clowder; a group of kittens is called a kindle.", category: "Animals" },
  { text: "Crocodiles cannot stick out their tongue — it is fused to the bottom of their mouth.", category: "Animals" },
  { text: "Flamingos are not naturally pink — their pink colour comes from carotenoid pigments in the algae and shrimp they eat.", category: "Animals" },
  { text: "A snail's slime is so effective at reducing friction that it can glide over the edge of a razor blade without harm.", category: "Animals" },
  { text: "Honey bees must visit about 2 million flowers to make one pound of honey, flying around 88,000 km in the process.", category: "Animals" },
  { text: "A group of jellyfish is called a bloom or a smack — and jellyfish have no brains, hearts, or bones.", category: "Animals" },
  { text: "The tongue of the blue whale is so large that about 50 full-grown people could stand on it.", category: "Animals" },
  { text: "Ravens have been observed pulling each other's tails as a form of play — they are considered among the most playful birds.", category: "Animals" },
  { text: "Polar bears have black skin beneath their white fur, which helps absorb solar heat more efficiently.", category: "Animals" },
  { text: "A group of ravens is called an unkindness; a group of crows is called a murder.", category: "Animals" },
  { text: "Seahorses are the only animal species on Earth in which the male carries and gives birth to the offspring.", category: "Animals" },
  // ─── History (continued) ────────────────────────────────────────────────────
  { text: "Ancient Egyptians shaved off their eyebrows to mourn the death of their cat.", category: "History" },
  { text: "The first public zoo opened in Vienna in 1752 — originally as a menagerie for the Habsburg imperial family.", category: "History" },
  { text: "Bubble gum was invented in 1928 by Walter Diemer — he made it pink because it was the only colouring available.", category: "History" },
  { text: "In ancient Rome, being left-handed was considered unlucky — the word 'sinister' comes from the Latin for 'left'.", category: "History" },
  { text: "The Colosseum in Rome could hold up to 80,000 spectators and had a retractable fabric roof called the velarium.", category: "History" },
  { text: "Marie Curie is the only person to have won Nobel Prizes in two different sciences — Physics (1903) and Chemistry (1911).", category: "History" },
  { text: "The original Olympic Games in ancient Greece lasted five days and included chariot racing, wrestling, and the pentathlon.", category: "History" },
  { text: "The Titanic was declared unsinkable before its maiden voyage — when it sank in 1912, it carried only enough lifeboats for half the passengers.", category: "History" },
  { text: "Ancient Sumerians invented writing (cuneiform) about 5,000 years ago, primarily to keep accounts of grain and livestock.", category: "History" },
  { text: "The Black Death (1347–1351) killed an estimated one-third of Europe's population — around 25 million people.", category: "History" },
  // ─── Science (continued) ────────────────────────────────────────────────────
  { text: "Rubber bands last longer when refrigerated because lower temperatures slow the degradation of their polymer chains.", category: "Science" },
  { text: "The human body emits a faint glow — bioluminescence about 1,000 times weaker than what the human eye can detect.", category: "Science" },
  { text: "A teaspoon of the soil in your garden can contain more microorganisms than there are people on Earth.", category: "Science" },
  { text: "Colder air is actually denser and heavier than warm air — which is why hot air balloons rise.", category: "Science" },
  { text: "The driest place on Earth is the Atacama Desert in Chile — some weather stations there have never recorded rain.", category: "Science" },
  { text: "Nuclear fusion powers the Sun — it fuses 620 million tonnes of hydrogen into helium every single second.", category: "Science" },
  { text: "Black holes don't actually suck — their gravity is no stronger than a star of equal mass; they just don't have outward radiation pressure to counterbalance.", category: "Science" },
  { text: "CRISPR-Cas9, discovered in 2012, allows scientists to edit genes with a precision equivalent to finding a single word in a library and correcting a typo.", category: "Science" },
  { text: "Einstein's general relativity predicted that massive objects would bend light — confirmed during the 1919 solar eclipse by Arthur Eddington.", category: "Science" },
  { text: "The human microbiome — all the bacteria, viruses, and fungi living in and on us — collectively weigh about the same as the human brain.", category: "Science" },
  // ─── Geography (continued) ──────────────────────────────────────────────────
  { text: "The Amazon River has no bridges across it — the entire length passes through rainforest and jungle with no road crossings.", category: "Geography" },
  { text: "Finland has roughly 188,000 lakes — more lakes per area than any other country in the world.", category: "Geography" },
  { text: "The Nile flows northward — about 90% of the world's rivers flow south, but the Nile defies this with a northward course.", category: "Geography" },
  { text: "Turkey is the only country in the world that lies on two continents — split between Europe and Asia by the Bosphorus Strait.", category: "Geography" },
  { text: "The Great Barrier Reef is so large it has its own postcode — at around 2,300 km long it is the world's largest living structure.", category: "Geography" },
  { text: "Greenland is the world's largest island, yet only about 56,000 people live there — roughly the population of a small town.", category: "Geography" },
  { text: "The Mariana Trench is 11 km deep — if Everest were placed at the bottom, its peak would still be over 2 km underwater.", category: "Geography" },
  { text: "Iceland has no army and has been at peace since 1944 — it is consistently ranked among the world's most peaceful countries.", category: "Geography" },
  { text: "The Sahara Desert contains the world's largest supply of underground fresh water — the Nubian Sandstone Aquifer System.", category: "Geography" },
  { text: "Bolivia has two capital cities — Sucre is the constitutional capital and La Paz is the seat of government.", category: "Geography" },
  // ─── Mathematics (continued) ────────────────────────────────────────────────
  { text: "The Königsberg Bridge Problem (1736) was the first problem solved using graph theory — Euler proved it was impossible to cross all seven bridges exactly once.", category: "Mathematics" },
  { text: "The sum of all angles in any triangle always equals exactly 180° in flat (Euclidean) geometry.", category: "Mathematics" },
  { text: "A Möbius strip has only one surface and one edge — you can draw a line along its entire length without lifting your pen.", category: "Mathematics" },
  { text: "Prime numbers have been used in cryptography since the 1970s; your bank uses them every time you make a payment online.", category: "Mathematics" },
  { text: "The four-colour theorem states that any map can be coloured with just four colours so no two adjacent regions share the same colour.", category: "Mathematics" },
  { text: "In base 12 (dozenal), fractions like 1/3 and 1/4 are clean decimals — this is why clocks, eggs, and dozens are all multiples of 12.", category: "Mathematics" },
  // ─── Language (continued) ───────────────────────────────────────────────────
  { text: "The word 'set' has the most definitions of any word in the English language — the Oxford English Dictionary gives it over 430.", category: "Language" },
  { text: "Mandarin Chinese is the most spoken language in the world by native speakers — about 920 million people.", category: "Language" },
  { text: "English borrows about 60% of its vocabulary from Latin and French — a legacy of the Norman Conquest of 1066.", category: "Language" },
  { text: "The Silbo Gomero is a whistled language from the Canary Islands that can carry a conversation over 3 km of mountain terrain.", category: "Language" },
  { text: "Pirahã, a language spoken by an Amazonian tribe, lacks numbers, colours, or the ability to express the past or future.", category: "Language" },
  { text: "The word 'checkmate' comes from the Arabic 'shah mat' — meaning 'the king is dead'.", category: "Language" },
  { text: "The @ symbol in Czech is called 'zavináč' — meaning rollmop herring — and in Italian it is known as chiocciola (snail).", category: "Language" },
  // ─── Food (continued) ───────────────────────────────────────────────────────
  { text: "Pineapple contains bromelain, an enzyme that breaks down proteins — which is why pineapple makes your mouth tingly and why you cannot use raw pineapple in gelatin.", category: "Food" },
  { text: "The world's hottest chilli pepper, the Carolina Reaper, measures over 2 million Scoville Heat Units — roughly 200 times hotter than jalapeños.", category: "Food" },
  { text: "Figs technically contain tiny dead wasps inside them — fig plants and fig wasps have a co-evolutionary mutualism where wasps pollinate figs from within.", category: "Food" },
  { text: "The word 'avocado' comes from the Nahuatl word 'ahuacatl', which also meant testicle — the Aztecs considered the fruit an aphrodisiac.", category: "Food" },
  { text: "Pistachios are technically seeds of a drupe (a stone fruit), related to mangoes and cashews.", category: "Food" },
  { text: "Canned food was invented over 30 years before the tin-opener — soldiers had to use bayonets or rocks to open early tins.", category: "Food" },
  { text: "The Big Mac Index was introduced by The Economist in 1986 as an informal way to measure purchasing power parity between currencies.", category: "Food" },
  // ─── Technology (continued) ─────────────────────────────────────────────────
  { text: "The first iPhone was announced by Steve Jobs on January 9, 2007 — he called it 'an iPod, a phone, and an internet communicator' rolled into one.", category: "Technology" },
  { text: "The entire internet is estimated to weigh about 50 grams — the mass of all the electrons in motion at any given moment.", category: "Technology" },
  { text: "Ada Lovelace wrote the world's first computer algorithm in 1843 — for a machine that wouldn't be built for another century.", category: "Technology" },
  { text: "The first computer virus, the 'Creeper' program, appeared in 1971 on ARPANET — it displayed 'I'm the creeper, catch me if you can!'", category: "Technology" },
  { text: "3D printing technology was invented in 1983 by Chuck Hull — today it is used to print everything from prosthetic limbs to houses.", category: "Technology" },
  { text: "The GPS system is so precise that it requires corrections from both special and general relativity to remain accurate.", category: "Technology" },
  { text: "There are roughly 5 billion smartphone users worldwide — more than 60% of the global population.", category: "Technology" },
  // ─── Psychology (continued) ─────────────────────────────────────────────────
  { text: "The 'Benjamin Franklin effect' suggests that doing someone a favour makes you like them more — not the other way around.", category: "Psychology" },
  { text: "Nostalgia was once classified as a medical disease — Swiss doctors in the 17th century diagnosed soldiers who longed for home.", category: "Psychology" },
  { text: "People overestimate their ability to resist temptation — this is called the 'restraint bias', and it often leads to overconsumption.", category: "Psychology" },
  { text: "The spotlight effect is the tendency to believe people are paying far more attention to us than they actually are.", category: "Psychology" },
  { text: "Studies show that writing down your worries before an exam significantly improves performance — it offloads cognitive burden.", category: "Psychology" },
  { text: "Social media platforms are deliberately designed using variable reward schedules — the same mechanism that makes slot machines addictive.", category: "Psychology" },
  { text: "The 'IKEA effect' describes how people place a disproportionately high value on things they helped create themselves.", category: "Psychology" },
  // ─── Nature (continued) ─────────────────────────────────────────────────────
  { text: "Sequoia trees can live over 3,000 years — the oldest known, General Sherman, is about 2,200 years old and still growing.", category: "Nature" },
  { text: "Lightning creates a narrow tube of plasma hotter than the Sun's surface, which is why thunder follows — it's the shockwave of that superheated air.", category: "Nature" },
  { text: "Coral reefs cover less than 1% of the ocean floor but support roughly 25% of all marine species.", category: "Nature" },
  { text: "Sunflowers track the Sun from east to west during the day — a behaviour called heliotropism — but only while they are young and growing.", category: "Nature" },
  { text: "A single teaspoon of healthy soil contains more living organisms than there are people on Earth.", category: "Nature" },
  { text: "The Mojave Desert blooms unpredictably once every several years when rainfall is just right — it becomes carpeted in wildflowers for a few weeks.", category: "Nature" },
  { text: "Deep-sea fish like the anglerfish live in total darkness and have evolved their own bioluminescent lures to attract prey.", category: "Nature" },
  // ─── Art & Music (continued) ────────────────────────────────────────────────
  { text: "The Great Wall of China, the Eiffel Tower, and the Taj Mahal were originally considered eyesores by critics of their time.", category: "Art & Music" },
  { text: "Beethoven's Ninth Symphony premiered in 1824 — he was so deaf he could not hear the applause and had to be turned around to see it.", category: "Art & Music" },
  { text: "The word 'jazz' may derive from a West African word for rapid patter — its exact etymology remains debated.", category: "Art & Music" },
  { text: "The Sistine Chapel is 40 metres long and 13 metres wide — roughly the same proportions as the Temple of Solomon described in the Old Testament.", category: "Art & Music" },
  { text: "Frida Kahlo painted 55 self-portraits out of a total of 143 works — she said she painted herself because she was the subject she knew best.", category: "Art & Music" },
  { text: "The world's best-selling album of all time is Michael Jackson's Thriller (1982), with an estimated 66 million copies sold.", category: "Art & Music" },
  // ─── Sports (continued) ─────────────────────────────────────────────────────
  { text: "The Tour de France was created in 1903 by a cycling magazine to boost its own readership.", category: "Sports" },
  { text: "Basketball was invented by Dr. James Naismith in 1891 using a peach basket — early players had to retrieve the ball from the basket after each score.", category: "Sports" },
  { text: "Roger Federer has played over 1,500 professional tennis matches and holds the record for most Grand Slam singles titles won over consecutive years.", category: "Sports" },
  { text: "Cricket is the second most popular sport in the world after football, with about 2.5 billion fans primarily across South Asia and the Caribbean.", category: "Sports" },
  { text: "The marathon distance — 42.195 km — was standardised only at the 1908 London Olympics to start at Windsor Castle and end in front of the royal box.", category: "Sports" },
  { text: "Competitive eating is sanctioned as a professional sport in the USA — the world record for hot dogs eaten in 10 minutes is 76.", category: "Sports" },
  // ─── Inventions (continued) ─────────────────────────────────────────────────
  { text: "The automatic door was invented by Dee Horton and Lew Hewitt in 1954 after watching a mat actuation mechanism at a dry cleaner.", category: "Inventions" },
  { text: "Penicillin was discovered accidentally in 1928 when Alexander Fleming noticed mould killing bacteria in a petri dish he had forgotten to cover.", category: "Inventions" },
  { text: "The first photograph ever taken was by Joseph Nicéphore Niépce in 1826 — it required an 8-hour exposure and shows a rooftop view from his window.", category: "Inventions" },
  { text: "Liquid Paper (correction fluid) was invented by Bette Nesmith Graham, mother of one of The Monkees' Mike Nesmith, while working as a secretary in 1951.", category: "Inventions" },
  { text: "The Slinky was invented by accident when naval engineer Richard James knocked a tension spring off a shelf in 1943 and watched it walk down steps.", category: "Inventions" },
  { text: "Duct tape was originally called 'duck tape' — invented during WWII for US military use to keep moisture out of ammunition cases.", category: "Inventions" },
  // ─── Society (continued) ────────────────────────────────────────────────────
  { text: "The library of Alexandria, the ancient world's greatest repository of knowledge, was not destroyed in a single event — it declined over centuries.", category: "Society" },
  { text: "English is not the most spoken language — Mandarin has roughly twice as many native speakers, but English has far more total speakers when second-language users are counted.", category: "Society" },
  { text: "The world produces enough food to feed 10 billion people — hunger is a distribution and poverty problem, not a production problem.", category: "Society" },
  { text: "The top 10 companies in the world by market cap in 2024 have a combined valuation larger than the GDP of every country except the United States and China.", category: "Society" },
  { text: "Approximately 90% of the world's currency exists only as digital data — physical cash and coins represent less than 10% of global money.", category: "Society" },
  // ─── Quirky (continued) ─────────────────────────────────────────────────────
  { text: "The word 'muscle' comes from the Latin 'musculus', meaning little mouse — ancient Romans thought flexing muscles looked like a mouse moving under the skin.", category: "Quirky" },
  { text: "Honey bees are the only insects that produce food consumed by humans.", category: "Quirky" },
  { text: "A group of twelve or more cows is called a flink.", category: "Quirky" },
  { text: "The dot above the letters 'i' and 'j' has a name — it is called a tittle.", category: "Quirky" },
  { text: "The fingerprints of a koala are so similar to human fingerprints that they have been confused in crime scene investigations.", category: "Quirky" },
  { text: "Some species of jellyfish are 95% water — if left on a beach they virtually disappear in the sun.", category: "Quirky" },
  { text: "The fear of long words is called hippopotomonstrosesquippedaliophobia — widely considered a cruel irony.", category: "Quirky" },
  { text: "ABBA turned down one billion dollars to reunite in 2000 — they eventually released new music in 2021 instead, more than 40 years after their peak.", category: "Quirky" },
  { text: "The straw was invented 5,000 years ago in Mesopotamia — the earliest ones were made of gold.", category: "Quirky" },
  { text: "A duel between three people is called a truel — the mathematics of truel strategy are far more complex than a regular duel.", category: "Quirky" },
  // ─── Final 20 ────────────────────────────────────────────────────────────────
  { text: "The longest recorded flight of a chicken is 13 seconds.", category: "Quirky" },
  { text: "The first person convicted of speeding was Walter Arnold in 1896 — he was travelling at 13 km/h (8 mph), four times the legal limit.", category: "History" },
  { text: "Octopus ink contains a compound called tyrosinase, which can temporarily blind predators by disrupting their chemical senses.", category: "Animals" },
  { text: "The human body replaces roughly 30,000 to 40,000 dead skin cells every hour — about 2 kg of skin per year.", category: "Human Body" },
  { text: "Jupiter has at least 95 known moons — by far the most of any planet in our solar system.", category: "Space" },
  { text: "During the French Revolution, France briefly switched to a 10-hour clock with 100-minute hours and 100-second minutes — it lasted fewer than two years.", category: "History" },
  { text: "The speed of sound changes with temperature — at 20 °C it is about 343 m/s; at freezing point (0 °C) it slows to 331 m/s.", category: "Science" },
  { text: "There are 43 quintillion (4.3 × 10¹⁹) possible states of a standard Rubik's Cube, yet any state can be solved in at most 20 moves.", category: "Mathematics" },
  { text: "Norway is so far north that citizens above the Arctic Circle experience the 'midnight sun' — continuous daylight for weeks in summer.", category: "Geography" },
  { text: "The word 'robot' was coined in 1920 by Czech playwright Karel Čapek — from the Czech word robota, meaning forced labour.", category: "Language" },
  { text: "The oldest known musical instruments are bone flutes found in Germany, estimated to be over 40,000 years old.", category: "Art & Music" },
  { text: "The original formula for Coca-Cola actually contained trace amounts of cocaine from coca leaf extract until 1903.", category: "Food" },
  { text: "The first tweet was sent by Jack Dorsey on March 21, 2006, and read: 'just setting up my twttr'.", category: "Technology" },
  { text: "Loss aversion is twice as powerful as the equivalent pleasure of gain — losing £50 feels roughly twice as bad as finding £50 feels good.", category: "Psychology" },
  { text: "A forest can be recreated from scratch through a method called the Miyawaki technique, creating dense native forest in 20–30 years instead of 200.", category: "Nature" },
  { text: "The first commercial passenger flight took place on January 1, 1914 — from St Petersburg to Tampa, Florida, a distance of about 34 km by air.", category: "Inventions" },
  { text: "Roughly 1 in 200 men alive today is a direct descendant of Genghis Khan.", category: "Society" },
  { text: "William Shakespeare invented over 1,700 words still used in English today, including bedroom, lonely, generous, and swagger.", category: "History" },
  { text: "A group of hedgehogs is called an array; a group of porcupines is called a prickle.", category: "Animals" },
  { text: "An estimated 1 million species of plants and animals face extinction in the coming decades — this is the highest extinction rate in human history.", category: "Nature" },
];
